
export type Language = 'en' | 'hi' | 'te';

export type View = 'home' | 'disease-detection' | 'yield-prediction' | 'market-price' | 'training' | 'chatbot';

export type TranslationKey = 
  | 'appName'
  | 'navHome'
  | 'navDiseaseDetection'
  | 'navYieldPrediction'
  | 'navMarketPrice'
  | 'navTraining'
  | 'navChatbot'
  | 'language'
  | 'english'
  | 'hindi'
  | 'telugu'
  | 'selectLanguage'
  | 'welcomeMessage'
  | 'welcomeSubtitle'
  | 'exploreFeatures'
  | 'diseaseDetectionTitle'
  | 'diseaseDetectionDesc'
  | 'yieldPredictionTitle'
  | 'yieldPredictionDesc'
  | 'marketPriceTitle'
  | 'marketPriceDesc'
  | 'trainingTitle'
  | 'trainingDesc'
  | 'chatbotTitle'
  | 'chatbotDesc'
  | 'launch'
  | 'uploadImage'
  | 'detectDisease'
  | 'analyzing'
  | 'noFileSelected'
  | 'temperature'
  | 'humidity'
  | 'soilPH'
  | 'rainfall'
  | 'predictYield'
  | 'predicting'
  | 'marketPriceHeader'
  | 'priceChartTitle'
  | 'profitLossChartTitle'
  | 'months'
  | 'price'
  | 'profit'
  | 'loss'
  | 'trainModelHeader'
  | 'uploadDataset'
  | 'supportedFormats'
  | 'startTraining'
  | 'trainingProgress'
  | 'chatbotHeader'
  | 'chatbotPlaceholder'
  | 'chatbotWelcome'
  | 'jan' | 'feb' | 'mar' | 'apr' | 'may' | 'jun' | 'jul' | 'aug' | 'sep' | 'oct' | 'nov' | 'dec'
  | 'footerText';
